# Generated by Django 3.1 on 2020-08-20 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_path', models.CharField(max_length=35)),
                ('adult', models.BooleanField()),
                ('overview', models.TextField()),
                ('release_date', models.CharField(max_length=12)),
                ('genre_ids', models.TextField(validators=[django.core.validators.int_list_validator])),
                ('tmdb_id', models.IntegerField()),
                ('original_title', models.TextField()),
                ('original_language', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('backdrop_path', models.CharField(max_length=35)),
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('video', models.BooleanField()),
                ('video_average', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed')])),
                ('movies', models.ManyToManyField(to='apiapp.Movie')),
            ],
        ),
    ]
