# Generated by Django 3.1 on 2020-08-22 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_auto_20200820_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='recommended',
            field=models.ManyToManyField(related_name='recommended', to='apiapp.Movie'),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='codename',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed')]),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='movies',
            field=models.ManyToManyField(related_name='movies', to='apiapp.Movie'),
        ),
    ]
